---
# tasks file for common

# set timezone UTC+3/Moscow
- name: set timezone to Europe/Moscow
  community.general.timezone:
    name: "{{ timezone }}"

# mount and set swapfile to server
- block:
  - name: create a swap file
    shell: fallocate -l {{ swap_size }} /swapfile
    args:
      creates: /swapfile
    
  - name: set correct permissions
    file:
      path: /swapfile
      owner: root
      group: root
      mode: '0600'

  - name: make the swapfile
    shell: mkswap /swapfile
    when: ansible_facts.swapfree_mb == 0

  - name: enable the swap file
    shell: swapon /swapfile
    when: ansible_facts.swapfree_mb == 0

  - name: add swap file to fstab
    mount:
      name: none
      src: /swapfile
      fstype: swap
      opts: sw
      passno: 0
      dump: 0
      state: present

# set hostname to server
- name: set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
