---
- name: Check swap info into tmp files
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "swap"
    state: present
  check_mode: yes
  register: line_check
  changed_when: false

- name: deactivate swap file on remote host
  ansible.builtin.shell:
    cmd: swapoff -a
  when: line_check.changed == false

- name: Remove Swap from fstab
  ansible.builtin.mount:
    name: swap
    fstype: swap
    state: absent

- name: Delete swap file
  ansible.builtin.file:
    path: "{{ swap_path }}"
    state: absent
